name: flutter_login_page_ui
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:



  flutter:
    sdk: flutter

  location: 2.3.4
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_screenutil: ^0.4.2
  rflutter_alert: ^1.0.3
  http: ^0.12.0+2
#  jaguar_jwt: ^2.1.6
#  android_multiple_identifier: ^1.0.3
#  flutter_secure_storage: ^3.2.1+1
  localstorage: ^2.0.0
  imei_plugin: ^1.1.0
  sim_service: ^0.1.0
  shared_preferences: ^0.5.3+4

  google_maps_flutter: ^0.5.15+1
  poly: ^1.0.2

#  location: 2.3.5
  url_launcher: 5.0.2
  titled_navigation_bar: ^3.5.0
  font_awesome_flutter:

  time_machine:
  timezone: ^0.5.5
  intl: ^0.15.8
  percent_indicator: ^2.1.1+1

  jaguar_jwt: ^2.1.6

#  json_listview: ^0.1.0
#  circular_profile_avatar: ^1.0.2

#  json_listview:
  
#  timezone: ^0.5.5

#  geolocator: ^3.0.1
#  flutter_secure_storage: ^3.2.1+1
#  flutter_secure_storage: 3.2.1+1

#  firebase_core: 0.3.1+1
#  firebase_auth: 0.8.1+4
#  rflutter_alert: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter




# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/image_01.png
   - assets/image_02.png
   - assets/logo.png
   - assets/Kkh1.jpg
   - assets/Unknown.png
   - KKH_place.jpg

   - res/images/
   - res/images/ovo_logo.png
   - res/images/transfer.png
   - res/images/scan.png
   - res/images/user_id.png
   - res/images/listrik.png
   - res/images/pulsa.png
   - res/images/paket_data.png
   - res/images/pasca_bayar.png
   - res/images/bpjs.png
   - res/images/tv_kabel.png
   - res/images/asuransi.png
   - res/images/lihat_semua.png
   - res/images/banner2.png
   - res/images/banner1.png
   

#   - packages/timezone/data/latest.tzf


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/CustomIcons.ttf

  

    - family: Poppins-Bold
      fonts:
        - asset: assets/Poppins-Bold.ttf

    - family: Poppins-Medium
      fonts:
        - asset: assets/Poppins-Medium.ttf

    - family: THSarabun
      fonts:
        - asset: assets/THSarabun.ttf
          
  
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages


